FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine
WORKDIR /src

COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "TodoApp.dll"]